name: flutter_evertec_tmdb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  cupertino_icons: ^1.0.2
  domain:
    path: ./domain
  flutter:
    sdk: flutter
  infrastructure:
    path: ./infrastructure

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
