name: flutter_evertec_tmdb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  cupertino_icons: ^1.0.2
  domain:
    path: ./domain
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.2.0
  go_router: ^12.0.0
  infrastructure:
    path: ./infrastructure
  injectable: ^2.1.1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.1.1

flutter:
  uses-material-design: true
